#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: run-builder.sh --workdir DIR --contract DIR [--local-model TAG]

Runs the local Builder (with one retry), then escalates to Codex cloud.
If cloud also fails, exits with code 20 and requires engineer approval before
Claude may take over.

Variables: ADW_LOCAL_MODEL, ADW_TIMEOUT_SECONDS (600), ADW_RESULTS_DIR,
ADW_SKIP_LOCAL=1, ADW_CLOUD_MODEL (gpt-5.6-sol), ADW_GATE_TIMEOUT_SECONDS
(300), ADW_LOCAL_PROFILE, ADW_ENGINE_MODE (ladder|local-only|cloud-only)
(ollama-launch; generated by `ollama launch codex`).
EOF
}

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
WORKDIR=""
CONTRACT_DIR=""
LOCAL_MODEL=${ADW_LOCAL_MODEL:-}
LOCAL_PROFILE=${ADW_LOCAL_PROFILE:-ollama-launch}
LOCAL_PROFILE_FILE=${ADW_LOCAL_PROFILE_FILE:-"$HOME/.codex/${LOCAL_PROFILE}.config.toml"}
TIMEOUT_SECONDS=${ADW_TIMEOUT_SECONDS:-600}
GATE_TIMEOUT_SECONDS=${ADW_GATE_TIMEOUT_SECONDS:-300}
CLOUD_MODEL=${ADW_CLOUD_MODEL:-gpt-5.6-sol}
SKIP_LOCAL=${ADW_SKIP_LOCAL:-0}
ENGINE_MODE=${ADW_ENGINE_MODE:-ladder}
RESULTS_ROOT=${ADW_RESULTS_DIR:-"${TMPDIR:-/tmp}/adw-hybrid-builder-results"}

while (($#)); do
    case "$1" in
        --workdir) WORKDIR=${2:?}; shift 2 ;;
        --contract) CONTRACT_DIR=${2:?}; shift 2 ;;
        --local-model) LOCAL_MODEL=${2:?}; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

[[ -n "$WORKDIR" && -n "$CONTRACT_DIR" ]] || { usage >&2; exit 2; }
case "$ENGINE_MODE" in
    ladder|local-only|cloud-only) ;;
    *) printf 'Invalid ADW_ENGINE_MODE: %s\n' "$ENGINE_MODE" >&2; exit 2 ;;
esac
WORKDIR=$(cd -- "$WORKDIR" && pwd)
CONTRACT_DIR=$(cd -- "$CONTRACT_DIR" && pwd)
SPEC_FILE="$CONTRACT_DIR/spec.md"
GATE_FILE="$CONTRACT_DIR/gate.sh"
ALLOWED_FILE="$CONTRACT_DIR/allowed-files.txt"

for required in "$SPEC_FILE" "$GATE_FILE" "$ALLOWED_FILE"; do
    [[ -f "$required" ]] || { printf 'Missing contract file: %s\n' "$required" >&2; exit 2; }
done
command -v codex >/dev/null || { printf 'Missing codex CLI\n' >&2; exit 2; }
command -v git >/dev/null || { printf 'Missing git\n' >&2; exit 2; }
command -v timeout >/dev/null || { printf 'Missing timeout\n' >&2; exit 2; }
command -v python3 >/dev/null || { printf 'Missing python3\n' >&2; exit 2; }
command -v sha256sum >/dev/null || { printf 'Missing sha256sum\n' >&2; exit 2; }
command -v tar >/dev/null || { printf 'Missing tar\n' >&2; exit 2; }
git -C "$WORKDIR" rev-parse --is-inside-work-tree >/dev/null

worktree_status() {
    git -C "$WORKDIR" status --porcelain -- . \
        ':!.claude/adw-runs' ':!.claude/worktrees' ':!adw/waves'
}

if [[ -n "$(worktree_status)" ]]; then
    printf 'The worktree must start clean; existing changes will not be risked.\n' >&2
    exit 2
fi

START_COMMIT=$(git -C "$WORKDIR" rev-parse HEAD)
GATE_HASH=$(sha256sum "$GATE_FILE" | awk '{print $1}')
RUN_ID=$(date -u +%Y%m%dT%H%M%SZ)-$$
RUN_DIR="$RESULTS_ROOT/$RUN_ID"
mkdir -p "$RUN_DIR"
METRICS_FILE="$RESULTS_ROOT/metrics.jsonl"
touch "$METRICS_FILE"

mapfile -t ALLOWED < <(sed -e 's/[[:space:]]*#.*$//' -e '/^[[:space:]]*$/d' "$ALLOWED_FILE")
((${#ALLOWED[@]} > 0)) || { printf 'allowed-files.txt is empty\n' >&2; exit 2; }

reset_builder_changes() {
    git -C "$WORKDIR" reset --hard "$START_COMMIT" >/dev/null
    git -C "$WORKDIR" clean -fd \
        -e .claude/adw-runs/ -e .claude/worktrees/ -e adw/waves/ >/dev/null
}

# Local-tier preflight: profile present, daemon reachable, and model tag present.
# Failure is infrastructure, not model capability, and stops the run.
preflight_local() {
    local tags
    command -v curl >/dev/null \
        || { printf 'local preflight: curl is missing\n' >&2; return 1; }
    [[ -f "$LOCAL_PROFILE_FILE" ]] \
        || { printf 'local preflight: profile %s is missing (run: ollama launch codex)\n' "$LOCAL_PROFILE" >&2; return 1; }
    tags=$(curl -sf --max-time 5 http://localhost:11434/api/tags 2>/dev/null) \
        || { printf 'local preflight: Ollama is not responding at localhost:11434\n' >&2; return 1; }
    if ! python3 -c '
import json
import sys

model = sys.argv[1]
payload = json.load(sys.stdin)
names = {
    value
    for item in payload.get("models", [])
    for value in (item.get("name"), item.get("model"))
    if value
}
raise SystemExit(0 if model in names else 1)
' "$LOCAL_MODEL" <<<"$tags"; then
        printf 'local preflight: tag %s is missing (ollama pull %s)\n' \
            "$LOCAL_MODEL" "$LOCAL_MODEL" >&2
        return 1
    fi
}

gate_untouched() {
    [[ "$(sha256sum "$GATE_FILE" | awk '{print $1}')" == "$GATE_HASH" ]]
}

scope_ok() {
    local changed path allowed match
    changed=$(changed_files)
    while IFS= read -r path; do
        [[ -z "$path" ]] && continue
        match=false
        for allowed in "${ALLOWED[@]}"; do
            [[ "$path" == "$allowed" ]] && match=true && break
        done
        [[ "$match" == true ]] || return 1
    done <<<"$changed"
}

changed_files() {
    {
        git -C "$WORKDIR" diff --name-only "$START_COMMIT" -- . \
            ':!.claude/adw-runs' ':!.claude/worktrees' ':!adw/waves'
        git -C "$WORKDIR" ls-files --others --exclude-standard -- . \
            ':!.claude/adw-runs' ':!.claude/worktrees' ':!adw/waves'
    } | sed '/^[[:space:]]*$/d' | sort -u
}

record_metric() {
    local engine=$1 model=$2 attempt=$3 verdict=$4 duration=$5 events=$6 note=$7
    local files=$8 outside=$9 gate_touched
    gate_touched=false; gate_untouched || gate_touched=true
    python3 "$SCRIPT_DIR/summarize_attempt.py" \
        --events "$events" --metrics "$METRICS_FILE" --run-id "$RUN_ID" \
        --contract "$(basename "$CONTRACT_DIR")" --engine "$engine" --model "$model" \
        --attempt "$attempt" --gate "$verdict" --duration "$duration" \
        --files "$files" --outside "$outside" --gate-touched "$gate_touched" --note "$note"
}

invoke_builder() {
    local engine=$1 model=$2 attempt=$3 feedback=${4:-}
    local attempt_dir="$RUN_DIR/${engine}-attempt-${attempt}"
    local prompt start end rc verdict note files outside
    mkdir -p "$attempt_dir"
    prompt=$(cat "$SPEC_FILE")
    if [[ -n "$feedback" ]]; then
        prompt+=$'\n\nLOOP-BACK. The previous gate failed. Fix only the cause within scope. stderr:\n'
        prompt+="$feedback"
    fi
    start=$(date +%s)
    set +e
    if [[ "$engine" == local ]]; then
        # Profile (from `ollama launch codex`) supplies the model catalog and
        # wire_api=responses. Plain `--oss` uses chat completions + fallback
        # metadata, which breaks gpt-oss tool calling (verified 2026-08-20).
        timeout "$TIMEOUT_SECONDS" codex exec --profile "$LOCAL_PROFILE" -m "$model" \
            --sandbox workspace-write --cd "$WORKDIR" --ephemeral --json \
            -o "$attempt_dir/last-message.txt" "$prompt" \
            >"$attempt_dir/events.jsonl" 2>"$attempt_dir/codex-stderr.txt"
    else
        timeout "$TIMEOUT_SECONDS" codex exec -m "$model" \
            --sandbox workspace-write --cd "$WORKDIR" --ephemeral --json \
            -o "$attempt_dir/last-message.txt" "$prompt" \
            >"$attempt_dir/events.jsonl" 2>"$attempt_dir/codex-stderr.txt"
    fi
    rc=$?
    set -e
    end=$(date +%s)

    files=$(changed_files)
    outside=false; scope_ok || outside=true
    verdict=FAIL; note="codex_rc=$rc"
    if ((rc == 124)); then
        verdict=TIMEOUT
    elif ((rc != 0)); then
        verdict=FAIL
    elif ! gate_untouched; then
        verdict=FAIL; note="gate_tamper"
    elif [[ "$outside" == true ]]; then
        verdict=FAIL; note="out_of_scope"
    else
        # Gate runs are timeout-capped too: a gate that mis-resolves its root
        # can crawl the filesystem for hours (seen in the field 2026-08-22).
        set +e
        (cd "$WORKDIR" && PYTHONDONTWRITEBYTECODE=1 timeout "$GATE_TIMEOUT_SECONDS" bash "$GATE_FILE") \
            >"$attempt_dir/gate-stdout.txt" 2>"$attempt_dir/gate-stderr.txt"
        gate_rc=$?
        set -e
        if ((gate_rc == 0)); then
            verdict=PASS; note=""
        elif ((gate_rc == 124)); then
            note="gate_timeout"
        else
            note="gate_fail"
        fi
    fi
    record_metric "$engine" "$model" "$attempt" "$verdict" "$((end - start))" \
        "$attempt_dir/events.jsonl" "$note" "$files" "$outside"
    printf '%s' "$verdict" >"$attempt_dir/verdict.txt"
    [[ "$verdict" == PASS ]]
}

if [[ -f "$CONTRACT_DIR/seed.patch" ]]; then
    git -C "$WORKDIR" apply "$CONTRACT_DIR/seed.patch"
    git -C "$WORKDIR" add -A
    git -C "$WORKDIR" -c user.name='adw-hybrid runner' -c user.email='adw-hybrid@local' \
        commit -m "chore: initial state $(basename "$CONTRACT_DIR")" >/dev/null
    START_COMMIT=$(git -C "$WORKDIR" rev-parse HEAD)
fi

if [[ "$ENGINE_MODE" != cloud-only && "$SKIP_LOCAL" != 1 ]]; then
    [[ -n "$LOCAL_MODEL" ]] || { printf 'Missing --local-model or ADW_LOCAL_MODEL\n' >&2; exit 2; }
    if ! preflight_local; then
        : >"$RUN_DIR/preflight-local.events.jsonl"
        record_metric local "$LOCAL_MODEL" 0 SKIP 0 \
            "$RUN_DIR/preflight-local.events.jsonl" "preflight_infra" "" false
        # No silent tier skipping (user policy 2026-08-20): the local tier is
        # mandatory. Fix the infrastructure, or set ADW_SKIP_LOCAL=1 as an
        # explicit engineer decision. Never auto-substitute a paid engine.
        printf 'Local preflight failed: local tier is required. Fix Ollama/profile or set ADW_SKIP_LOCAL=1 explicitly.\n' >&2
        exit 2
    else
        if invoke_builder local "$LOCAL_MODEL" 1; then
            printf 'PASS engine=local attempt=1 results=%s\n' "$RUN_DIR"
            exit 0
        fi
        feedback=$(
            cat "$RUN_DIR/local-attempt-1/gate-stdout.txt" \
                "$RUN_DIR/local-attempt-1/gate-stderr.txt" 2>/dev/null || true
        )
        if gate_untouched && scope_ok && invoke_builder local "$LOCAL_MODEL" 2 "$feedback"; then
            printf 'PASS engine=local attempt=2 results=%s\n' "$RUN_DIR"
            exit 0
        fi
        reset_builder_changes
    fi
fi

# Wave scheduling separates the tiers so the local GPU remains serial while
# independent cloud escalations may run concurrently. Exit 10 means genuine
# local failure with a clean reset; it is internal to the wave scheduler.
if [[ "$ENGINE_MODE" == local-only ]]; then
    printf 'ESCALATE_CLOUD contract=%s results=%s\n' "$(basename "$CONTRACT_DIR")" "$RUN_DIR" >&2
    exit 10
fi

if invoke_builder cloud "$CLOUD_MODEL" 1; then
    printf 'PASS engine=cloud attempt=1 results=%s\n' "$RUN_DIR"
    exit 0
fi

# Preserve evidence from the failed cloud attempt BEFORE resetting.
# builder-claude starts from the sealed commit (the same contract as every
# engine); dispatch-builder copies the diff into durable artifacts.
git -C "$WORKDIR" diff "$START_COMMIT" >"$RUN_DIR/cloud-final.diff" || true
changed_files >"$RUN_DIR/cloud-final.files" || true
# `git diff` omits untracked files. Preserve them before `git clean` so
# builder-claude receives complete evidence from the failed cloud candidate.
git -C "$WORKDIR" ls-files -z --others --exclude-standard \
    | tar -C "$WORKDIR" --null -T - -cf "$RUN_DIR/cloud-final-untracked.tar" \
    2>/dev/null || true
reset_builder_changes

printf 'ESCALATE_CLAUDE contract=%s results=%s\n' "$(basename "$CONTRACT_DIR")" "$RUN_DIR" >&2
exit 20
