import { access, constants } from "node:fs/promises"
import path from "node:path"

import { runProcess } from "./process.mjs"

export const GATE_WRAPPER = ".codegen-contract/gate.sh"

// The Builder may only run `bash .codegen-contract/gate.sh`, so every contract
// gate is materialized as that wrapper around the contract's real commands.
export function gateScript(commands) {
  return [
    "#!/usr/bin/env bash",
    "# Generated by the OpenCode codegen orchestrator. Do not edit.",
    "set -euo pipefail",
    ...commands.map((command) => `${command}`),
    'printf \'CONTRACT GATE: PASS\\n\'',
    "",
  ].join("\n")
}

function referencedScript(command) {
  const tokens = command.trim().split(/\s+/)
  for (const token of tokens.slice(0, 3)) {
    if (token.includes("/") || /\.(sh|py|mjs|js)$/.test(token)) return token
  }
  return null
}

async function executable(filePath) {
  try {
    await access(filePath, constants.R_OK)
    return true
  } catch {
    return false
  }
}

// GATE_READY means the way to judge the result exists before anyone codes:
// the commands resolve, and on the untouched baseline the gate behaves as the
// contract expects (it fails for new behavior, passes for pure refactors).
export async function checkGateReadiness({
  directory,
  contract,
  timeoutSeconds = 300,
  run = runProcess,
}) {
  const reasons = []
  let fixable = false
  const commands = contract?.verification?.commands ?? []
  const expected = contract?.verification?.expected_baseline ?? "fail"
  if (commands.length === 0) {
    return { ready: false, fixable: true, reasons: ["no-verification-commands"], baseline: [] }
  }
  for (const command of commands) {
    const script = referencedScript(command)
    if (script && !script.startsWith("-") && !(await executable(path.resolve(directory, script)))) {
      reasons.push(`missing-script:${script}`)
      fixable = true
    }
  }
  if (reasons.length > 0) return { ready: false, fixable, reasons, baseline: [] }

  const baseline = []
  let anyFailed = false
  for (const command of commands) {
    const result = await run(command, [], { cwd: directory, timeoutSeconds, shell: true })
    baseline.push({ command, exit_code: result.exitCode })
    if (result.exitCode !== 0) anyFailed = true
  }
  if (expected === "fail" && !anyFailed) {
    reasons.push("gate-passes-on-baseline")
    fixable = true
  }
  if (expected === "pass" && anyFailed) {
    reasons.push("gate-fails-on-baseline")
  }
  return { ready: reasons.length === 0, fixable, reasons, baseline }
}
